// <auto-generated />
using System;
using FlowChat.SocialGraphService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowChat.SocialGraphService.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228015740_AddContactAndSocialGraphProfileData")]
    partial class AddContactAndSocialGraphProfileData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowChat.SocialGraphService.Persistence.Entities.ContactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("UserSocialGraphId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserSocialGraphId");

                    b.HasIndex("OwnerUserId", "ContactUserId")
                        .IsUnique()
                        .HasDatabaseName("uq_contact_owner_contact");

                    b.ToTable("Contacts", null, t =>
                        {
                            t.HasCheckConstraint("chk_different_users", "\"OwnerUserId\" <> \"ContactUserId\"");
                        });
                });

            modelBuilder.Entity("FlowChat.SocialGraphService.Persistence.Entities.InvitationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddresseeId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequesterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RespondedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid?>("UserSocialGraphId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserSocialGraphId");

                    b.HasIndex("RequesterId", "AddresseeId", "Status")
                        .HasDatabaseName("ix_invitations_requester_addressee_status");

                    b.ToTable("Invitations", null, t =>
                        {
                            t.HasCheckConstraint("chk_invitation_different_users", "\"RequesterId\" <> \"AddresseeId\"");
                        });
                });

            modelBuilder.Entity("FlowChat.SocialGraphService.Persistence.Entities.UserSocialGraphEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsEmailVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPhoneVisible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTimeOffset>("LastModifiedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastModifiedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("uq_user_social_graph_user_id");

                    b.ToTable("UserSocialGraphs", (string)null);
                });

            modelBuilder.Entity("FlowChat.SocialGraphService.Persistence.Entities.ContactEntity", b =>
                {
                    b.HasOne("FlowChat.SocialGraphService.Persistence.Entities.UserSocialGraphEntity", "UserSocialGraph")
                        .WithMany("Contacts")
                        .HasForeignKey("UserSocialGraphId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UserSocialGraph");
                });

            modelBuilder.Entity("FlowChat.SocialGraphService.Persistence.Entities.InvitationEntity", b =>
                {
                    b.HasOne("FlowChat.SocialGraphService.Persistence.Entities.UserSocialGraphEntity", "UserSocialGraph")
                        .WithMany("Invitations")
                        .HasForeignKey("UserSocialGraphId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("UserSocialGraph");
                });

            modelBuilder.Entity("FlowChat.SocialGraphService.Persistence.Entities.UserSocialGraphEntity", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Invitations");
                });
#pragma warning restore 612, 618
        }
    }
}
