namespace FlowChat.RealtimeService.Infrastructure.Kafka;

public interface IKafkaSettingsManager
{
    RealtimeConnectionRegisteredProducerSettingsSection GetRealtimeConnectionRegisteredProducerSettingsSection();
    RealtimeConnectionUnregisteredProducerSettingsSection GetRealtimeConnectionUnregisteredProducerSettingsSection();
}
