// <auto-generated />
using System;
using FlowChat.RealtimeService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlowChat.RealtimeService.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260712181845_AddRealtimeGroupMembershipVersionTracker")]
    partial class AddRealtimeGroupMembershipVersionTracker
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowChat.RealtimeService.Persistence.Entities.RealtimeGroupMembershipReadModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("GroupType")
                        .HasColumnType("text");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId", "GroupType", "ResourceId");

                    b.ToTable("RealtimeGroupMembershipReadModels", (string)null);
                });

            modelBuilder.Entity("FlowChat.RealtimeService.Persistence.Entities.RealtimeGroupMembershipVersionTrackerReadModel", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("ConversationId");

                    b.ToTable("RealtimeGroupMembershipVersionTrackerReadModels", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
