<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture" Version="4.18.1" />
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="FluentAssertions" Version="8.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\FlowChat.SocialGraphService.API\FlowChat.SocialGraphService.API.csproj" />
    <ProjectReference Include="..\..\src\FlowChat.SocialGraphService.Domain\FlowChat.SocialGraphService.Domain.csproj" />
    <ProjectReference Include="..\..\src\FlowChat.SocialGraphService.Application\FlowChat.SocialGraphService.Application.csproj" />
    <ProjectReference Include="..\..\src\Workers\FlowChat.SocialGraphService.Consumers\FlowChat.SocialGraphService.Consumers.csproj" />
    <ProjectReference Include="..\..\src\FlowChat.SocialGraphService.Infrastructure\FlowChat.SocialGraphService.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\FlowChat.SocialGraphService.Persistence\FlowChat.SocialGraphService.Persistence.csproj" />
    <ProjectReference Include="..\..\..\Common\src\FlowChat.Shared.Domain\FlowChat.Shared.Domain.csproj" />
    <ProjectReference Include="..\..\..\Common\src\FlowChat.Core\FlowChat.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

</Project>
