CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324162219_InitialCreate') THEN
    CREATE TABLE "SilverbackOutboxMessages" (
        "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
        "Content" bytea NOT NULL,
        "Headers" character varying(1000),
        "EndpointName" character varying(500) NOT NULL,
        "DynamicEndpoint" character varying(1000),
        "Created" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_SilverbackOutboxMessages" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324162219_InitialCreate') THEN
    CREATE TABLE "UserProfiles" (
        "Id" uuid NOT NULL,
        "UserName" character varying(100) NOT NULL,
        "NormalizedUserName" character varying(100) NOT NULL,
        "DisplayName" character varying(120) NOT NULL,
        "AvatarUrl" character varying(500),
        "Bio" character varying(500),
        "IsActive" boolean NOT NULL,
        "LastSeenAtUtc" timestamp with time zone,
        "IsEmailVisible" boolean NOT NULL DEFAULT TRUE,
        "IsPhoneVisible" boolean NOT NULL DEFAULT TRUE,
        "CreatedBy" character varying(256) NOT NULL,
        "CreatedDate" timestamp with time zone NOT NULL,
        "LastModifiedBy" character varying(256) NOT NULL,
        "LastModifiedDate" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_UserProfiles" PRIMARY KEY ("Id")
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324162219_InitialCreate') THEN
    CREATE TABLE "Emails" (
        "Id" uuid NOT NULL,
        "UserProfileId" uuid NOT NULL,
        "Address" character varying(256) NOT NULL,
        "IsMain" boolean NOT NULL DEFAULT FALSE,
        "LastModifiedBy" text NOT NULL,
        "LastModifiedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Emails" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Emails_UserProfiles_UserProfileId" FOREIGN KEY ("UserProfileId") REFERENCES "UserProfiles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324162219_InitialCreate') THEN
    CREATE TABLE "Phones" (
        "Id" uuid NOT NULL,
        "UserProfileId" uuid NOT NULL,
        "Number" character varying(32) NOT NULL,
        "IsMain" boolean NOT NULL DEFAULT FALSE,
        "LastModifiedBy" text NOT NULL,
        "LastModifiedAtUtc" timestamp with time zone NOT NULL,
        CONSTRAINT "PK_Phones" PRIMARY KEY ("Id"),
        CONSTRAINT "FK_Phones_UserProfiles_UserProfileId" FOREIGN KEY ("UserProfileId") REFERENCES "UserProfiles" ("Id") ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324162219_InitialCreate') THEN
    CREATE UNIQUE INDEX uq_email_user_profile_address ON "Emails" ("UserProfileId", "Address");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324162219_InitialCreate') THEN
    CREATE UNIQUE INDEX uq_phone_user_profile_number ON "Phones" ("UserProfileId", "Number");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324162219_InitialCreate') THEN
    CREATE UNIQUE INDEX "IX_UserProfiles_UserName" ON "UserProfiles" ("UserName");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324162219_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260324162219_InitialCreate', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324180630_RenameAuditTimestampColumns') THEN
    ALTER TABLE "UserProfiles" DROP COLUMN "CreatedDate";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324180630_RenameAuditTimestampColumns') THEN
    ALTER TABLE "UserProfiles" DROP COLUMN "LastModifiedDate";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324180630_RenameAuditTimestampColumns') THEN
    ALTER TABLE "UserProfiles" ADD "CreatedAtUtc" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324180630_RenameAuditTimestampColumns') THEN
    ALTER TABLE "UserProfiles" ADD "LastModifiedAtUtc" timestamp with time zone;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324180630_RenameAuditTimestampColumns') THEN
    UPDATE "UserProfiles"
    SET "CreatedAtUtc" = CURRENT_TIMESTAMP,
        "LastModifiedAtUtc" = CURRENT_TIMESTAMP
    WHERE "CreatedAtUtc" IS NULL
       OR "LastModifiedAtUtc" IS NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324180630_RenameAuditTimestampColumns') THEN
    ALTER TABLE "UserProfiles" ALTER COLUMN "CreatedAtUtc" SET NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324180630_RenameAuditTimestampColumns') THEN
    ALTER TABLE "UserProfiles" ALTER COLUMN "LastModifiedAtUtc" SET NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324180630_RenameAuditTimestampColumns') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260324180630_RenameAuditTimestampColumns', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324182944_ModelUpdate') THEN
    ALTER TABLE "Phones" ADD "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324182944_ModelUpdate') THEN
    ALTER TABLE "Phones" ADD "CreatedBy" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324182944_ModelUpdate') THEN
    ALTER TABLE "Emails" ADD "CreatedAtUtc" timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324182944_ModelUpdate') THEN
    ALTER TABLE "Emails" ADD "CreatedBy" text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324182944_ModelUpdate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260324182944_ModelUpdate', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260324183247_NewUpdate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260324183247_NewUpdate', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328223751_AddEmailIsConfirmed') THEN
    ALTER TABLE "Emails" ADD "IsConfirmed" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260328223751_AddEmailIsConfirmed') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260328223751_AddEmailIsConfirmed', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260329111500_AddEmailIsAuth') THEN
    ALTER TABLE "Emails" ADD "IsAuth" boolean NOT NULL DEFAULT FALSE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260329111500_AddEmailIsAuth') THEN
    DROP INDEX uq_email_user_profile_address;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260329111500_AddEmailIsAuth') THEN
    UPDATE "Emails" AS e
    SET "IsAuth" = TRUE
    FROM (
        SELECT DISTINCT ON ("UserProfileId") "Id"
        FROM "Emails"
        ORDER BY "UserProfileId", "IsMain" DESC, "CreatedAtUtc", "Id"
    ) AS selected
    WHERE e."Id" = selected."Id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260329111500_AddEmailIsAuth') THEN
    CREATE UNIQUE INDEX uq_email_address ON "Emails" ("Address");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260329111500_AddEmailIsAuth') THEN
    CREATE UNIQUE INDEX uq_email_user_profile_auth ON "Emails" ("UserProfileId") WHERE "IsAuth" = TRUE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260329111500_AddEmailIsAuth') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260329111500_AddEmailIsAuth', '10.0.3');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260329155339_AutoMigration_20260329_175336') THEN
    ALTER TABLE "DataProtectionKeys" ALTER COLUMN "FriendlyName" DROP NOT NULL;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260329155339_AutoMigration_20260329_175336') THEN
    CREATE INDEX "IX_EmailVerificationRequests_UserProfileId" ON "EmailVerificationRequests" ("UserProfileId");
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260329155339_AutoMigration_20260329_175336') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260329155339_AutoMigration_20260329_175336', '10.0.3');
    END IF;
END $EF$;
COMMIT;

