<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FlowChat.Core\FlowChat.Core.csproj" />
    <ProjectReference Include="..\FlowChat.Shared.Application\FlowChat.Shared.Application.csproj" />
    <ProjectReference Include="..\FlowChat.Shared.Infrastructure\FlowChat.Shared.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.3" />
    <PackageReference Include="Silverback.Core" Version="5.0.0" />
    <PackageReference Include="Silverback.Integration.Kafka" Version="5.0.0" />
    <PackageReference Include="Silverback.Storage.EntityFramework" Version="5.0.0" />
  </ItemGroup>

</Project>
