<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FlowChat.RealtimeService.Application\FlowChat.RealtimeService.Application.csproj" />
    <ProjectReference Include="..\FlowChat.RealtimeService.Domain\FlowChat.RealtimeService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\src\FlowChat.Shared.Infrastructure\FlowChat.Shared.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\Common\src\FlowChat.Shared.Persistance\FlowChat.Shared.Persistance.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="Silverback.Storage.EntityFramework" Version="5.0.0" />
    <PackageReference Include="Silverback.Storage.PostgreSql" Version="5.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
